### ISSUE TITLE
Conditional logic between columns

### ISSUE THREAD

**Issue by dsamson** [tmconnect/ACF-Column-Field#4]
Is it possible to use conditional logic to show/hide fields when they are in 2 separate columns?
Seems like I can only use the conditional logic to show/hide fields that are nested in the same column.
Better yet it would be cool if I can hide/show an entire column using conditional logic.

**Comment by tmconnect** [comment]
Unfortunately, the problem is how ACF use the field conditions. Both fields of the conditional logic (the field with the conditional logic and the field that holds the value for the logic) must be placed in the same element in the DOM.

However, since the column plugin must modify the DOM tree, so that the columns can be split, the conditional logic only work in a column.

I have not found a solution for it.
