### ISSUE TITLE
Conditionals not working consistently across columns

### ISSUE THREAD

**Issue by michaelgrime** [tmconnect/ACF-Column-Field#6]
I have some radio button fields in one column which are showing and hiding different image fields in another column, using the the image fields' conditional rules.

In some field groups this works, but in others the conditional rules aren't recognised (hidden fields stay hidden).

Sorry to throw this as an issue, but I have tried many different configurations but can't seem to get it to work consistently in all cases. The only pattern I can see is that this happens when there are more than 5 image fields being toggled.

**Comment by tmconnect** [comment]
I can't believe that you can build a radio in one column that show/hide other fields in a second column. Because this is not possible with this plugin (see https://github.com/tmconnect/ACF-Column-Field/issues/4).

I think, that the situations that work for you the fields are all in the same column and in the cases where it doesn't work the fields are in different columns.

Sorry - but there's no solution...

**Comment by michaelgrime** [comment]
You're correct: I've tried to replicate the case where I thought conditionals worked between columns, but I can't, I must have been mistaken.

Thanks for your quick response!
